export enum CalendarName {
  ALL = 'all',
  EMMAUS = 'emmaus',
  INZERSDORF = 'inzersdorf',
  NEUSTIFT = 'neustift',
  INZERSDORF_ORGAN = 'inzersdorf-organ',
}

export const CALENDAR_INFOS: Record<CalendarName, CalendarInfo> = {
  [CalendarName.ALL]: {
    id: CalendarName.ALL,
    calendarId: 'admin@tesarekplatz.at',
    className: '',
    borderColor: '',
    fullName: '',
    shortName: '',
    tagName: '',
    address: '',
    websiteUrl: '',
    websiteDisplay: '',
    image: '',
    dot: '',
  },
  [CalendarName.EMMAUS]: {
    id: CalendarName.EMMAUS,
    borderColor: 'border-emmaus',
    calendarId: 'u08nlhov79dkit0ffi993o6tuk@group.calendar.google.com',
    className: 'bg-emmaus text-white',
    fullName: 'Pfarre Emmaus am Wienerberg',
    shortName: 'Emmaus',
    tagName: 'Emmaus',
    address: 'Tesarekplatz 2, 1100 Wien',
    image: '/logo/parish_emmaus.svg',
    websiteUrl: 'https://emmaus.wien/',
    websiteDisplay: 'emmaus.wien',
    dot: '/dot/edot.svg',
  },
  [CalendarName.INZERSDORF]: {
    id: CalendarName.INZERSDORF,
    calendarId: '4fgiuth4nbbi5uqfa35tidnl84@group.calendar.google.com',
    className: 'bg-inzersdorf text-white',
    borderColor: 'border-inzersdorf',
    fullName: 'Pfarre Inzersdorf (St. Nikolaus)',
    shortName: 'St. Nikolaus',
    tagName: 'Nikolaus',
    address: 'Inzersdorf Kirchenplatz 1, 1230 Wien',
    image: '/logo/parish_inzersdorf.svg',
    websiteUrl: 'https://pfarresanktnikolaus.at',
    websiteDisplay: 'pfarresanktnikolaus.at',
    dot: '/dot/idot.svg',
  },
  [CalendarName.NEUSTIFT]: {
    id: CalendarName.NEUSTIFT,
    calendarId: 'occ77f3f7sderl9e3b4jdnr5ek@group.calendar.google.com',
    className: 'bg-neustift',
    borderColor: 'border-neustift',
    fullName: 'Pfarre Inzersdorf-Neustift',
    shortName: 'Neustift',
    tagName: 'Neustift',
    address: 'Don-Bosco-Gasse 14, 1230 Wien',
    image: '/logo/parish_neustift.svg',
    websiteUrl: 'https://www.erzdioezese-wien.at/pages/pfarren/9233',
    websiteDisplay: 'pfarreinzersdorfneustift.at',
    dot: '/dot/ndot.svg',
  },
  [CalendarName.INZERSDORF_ORGAN]: {
    id: CalendarName.INZERSDORF_ORGAN,
    calendarId: '3i1uurj6bgl1q91l1peejmfa80@group.calendar.google.com',
    className: 'bg-inzersdorf',
    fullName: '',
    borderColor: 'border-inzersdorf',
    shortName: '',
    tagName: '',
    address: '',
    websiteUrl: '',
    websiteDisplay: '',
    image: '',
    dot: ''
  },
};
export const getCalendarInfo = (calendar: CalendarName): CalendarInfo => {
  return CALENDAR_INFOS[calendar];
};

export interface CalendarInfo {
  id: CalendarName,
  calendarId: string,
  borderColor: string,
  className: string,
  fullName: string,
  shortName: string,
  tagName: string,
  address: string,
  image: string,
  websiteUrl: string,
  websiteDisplay: string,
  dot: string,
}
