name: Google Token Refresh
on:
  schedule:
    - cron:  '0 4 * * 1'
jobs:
  Google-Token-Refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: npm i
      - run: npm run refresh-google
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          COCKPIT_TOKEN: ${{ secrets.COCKPIT_TOKEN }}
          COCKPIT_HOST: ${{ secrets.COCKPIT_HOST }}